- name: Backup running-config from all devices
  hosts: all_devices
  gather_facts: no
  tasks:
    - name: Get running configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: running_config
      ignore_errors: yes

    - name: Save running configuration to local file
      copy:
        content: "{{ running_config.stdout[0] }}"
        dest: "/home/vboxuser/backups/{{ inventory_hostname }}_running.cfg"
      ignore_errors: yes

    - name: Send job notification email
      mail:
        host: smtp.gmail.com
        port: 587
        username: "zxcvuiop2414@gmail.com"
        password: "ndtlwhkfktrxaaqx"
        to: "zxcvuiop2414@gmail.com"
        subject: "Backup Job Notification"
        body: |
          Playbook: Backup running-config
          Status: {{ 'FAILED' if running_config is failed else 'SUCCESS' }}
          Hosts processed: {{ ansible_play_hosts_all | join(', ') }}
      delegate_to: localhost
      run_once: true
