---
- name: Backup running-config from all devices
  hosts: all_devices
  gather_facts: no
  vars:
    email_to: "zxcvuiop2414@gmail.com"
  tasks:

    - name: Initialize failed hosts list
      set_fact:
        failed_hosts: []

    - name: Get running configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: running_config
      ignore_errors: yes

    - name: Add failed host to list
      set_fact:
        failed_hosts: "{{ failed_hosts + [inventory_hostname] }}"
      when: running_config is failed

    - name: Save running configuration to local file
      copy:
        content: "{{ running_config.stdout[0] | default('No output') }}"
        dest: "/home/vboxuser/backups/{{ inventory_hostname }}_running.cfg"
      when: running_config is succeeded

    - name: Set playbook status
      set_fact:
        playbook_status: "{{ 'FAILED' if failed_hosts | length > 0 else 'SUCCESS' }}"

    - name: Send email notification
      mail:
        host: "smtp.gmail.com"
        port: 587
        username: "zxcvuiop2414@gmail.com"
        password: "ndtlwhkfktrxaaqx"
        to: "{{ email_to }}"
        subject: "Backup Playbook {{ playbook_status }}"
        body: |
          The backup playbook has completed.
          Status: {{ playbook_status }}

          {% if failed_hosts | length > 0 %}
          Failed hosts: {{ failed_hosts | join(', ') }}
          {% else %}
          All hosts backed up successfully.
          {% endif %}
        secure: starttls
